name: "universal_model"
backend: "python"
max_batch_size: 0
input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ 3 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 3 ]
  }
]
